pdx215: sepolicy: drop duplicate health policy
* You will also need to run
rm -rf hardware/lineage/interfaces/health
since Alpha has merged AIDL Health

FAILED: out/target/product/pdx215/obj/ETC/file_contexts.bin_intermediates/file_contexts.device.sorted.tmp
/bin/bash -c "(out/host/linux-x86/bin/checkfc -e out/target/product/pdx215/obj/ETC/precompiled_sepolicy_intermediates/precompiled_sepolicy out/target/product/pdx215/obj/ETC/file_contexts.bin_intermediates/file_contexts.device.tmp ) && (out/host/linux-x86/bin/fc_sort -i out/target/product/pdx215/obj/ETC/file_contexts.bin_intermediates/file_contexts.device.tmp -o out/target/product/pdx215/obj/ETC/file_contexts.bin_intermediates/file_contexts.device.sorted.tmp )"
out/target/product/pdx215/obj/ETC/file_contexts.bin_intermediates/file_contexts.device.tmp: Multiple same specifications for /(vendor|system/vendor)/bin/hw/vendor\.lineage\.health-service\.default.
Error: could not load context file from out/target/product/pdx215/obj/ETC/file_contexts.bin_intermediates/file_contexts.device.tmp

Signed-off-by: saku-bruh <notwolfyy@gmail.com>